const GET_VEHICLE_DOOR_STATUS = "VEHICLE/GET_VEHICLE_DOOR_STATUS";
const UPDATE_VEHICLE_DOOR_STATUS = "VEHICLE/UPDATE_VEHICLE_DOOR_STATUS";



const actionTypes = {
    GET_VEHICLE_DOOR_STATUS,
    UPDATE_VEHICLE_DOOR_STATUS
}

export default actionTypes;