const GET_VEHICLES = "VEHICLE/GET_VEHICLES";
const GET_VEHICLE_DETAILS = "VEHICLE/GET_VEHICLE_DETAILS";
const GET_VEHICLE_DOOR_STATUS = "VEHICLE/GET_VEHICLE_DOOR_STATUS";
const UPDATE_VEHICLE_DOOR_STATUS = "VEHICLE/UPDATE_VEHICLE_DOOR_STATUS";



const actionTypes = {
    GET_VEHICLES,
    GET_VEHICLE_DETAILS,
    GET_VEHICLE_DOOR_STATUS,
    UPDATE_VEHICLE_DOOR_STATUS
}

export default actionTypes;